variables:
  LC_ALL: "en_US.UTF-8" # Needed for xcpretty to work

stages:
  - test
  - deploy

Test:
  stage: test
  parallel:
    matrix:
      - DESTINATION:
        - 'platform=iOS Simulator,name=iPad (10th generation)'
        - 'platform=iOS Simulator,name=iPhone 14'
  script:
    - xcodebuild clean -project ImageProc.xcodeproj -scheme ImageProc | xcpretty
    - xcodebuild test -project ImageProc.xcodeproj -scheme ImageProcTests -destination "$DESTINATION" | xcpretty -s

Deploy:
  stage: deploy
  script:
    - pod spec lint ImageProc.podspec
    - CURRENT_VERSION=`sh .version` && git tag $CURRENT_VERSION
    - git push --tags
    - pod trunk push
