variables:
  LC_ALL: "en_US.UTF-8" # Needed for xcpretty to work

stages:
  - test
  - release

Test:
  stage: test
  parallel:
    matrix:
      - DESTINATION:
        - 'platform=iOS Simulator,name=iPad (10th generation)'
        - 'platform=iOS Simulator,name=iPhone 14'
  script:
    - echo "Dry-run on $DESTINATION"
    # - xcodebuild clean -project ImageProc.xcodeproj -scheme ImageProc | xcpretty
    # - xcodebuild test -project ImageProc.xcodeproj -scheme ImageProcTests -destination "$DESTINATION" | xcpretty -s

Release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Publishing ImageProc on CocoaPods"
    - pod spec lint ImageProc.podspec
    - pod trunk register andrea.ruffino@hotmail.fr --description='CI Automation'
    - pod trunk push
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
